global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'pratapsahoo772@gmail.com'
  smtp_auth_username: 'pratapsahoo772@gmail.com'
  smtp_auth_password: 'hbev rhnv wqxo ogwk'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'pratapsahoo772@gmail.com'
        from: 'pratapsahoo772@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'pratapsahoo772@gmail.com'
        auth_password: 'hbev rhnv wqxo ogwk'
        require_tls: true
        send_resolved: true
