spring:
  application:
    name: enterprise-devops-cicd-monitoring-platform

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: Enterprise DevOps CI/CD Monitoring Platform
    version: 1.0.0
    description: Production Ready Enterprise DevOps CI/CD Monitoring Platform
