spring:
  application:
    name: enterprise-devops-cicd-monitoring-platform


server:
  port: ${SERVER_PORT:8081}


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

    info:
      enabled: true

  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}


info:
  app:
    name: Enterprise DevOps CI/CD Monitoring Platform
    version: 1.0.0
    description: Production Ready Enterprise DevOps CI/CD Monitoring Platform
    java-version: 21
    spring-boot-version: 3.5.3


app:
  name: Enterprise DevOps CI/CD Monitoring Platform
  version: 1.0.0

  security:
    username: admin
    password: admin123
